Rework login button
nr23730/cbioportal-frontend pull request #82
Opened 2022-05-11 11:34 UTC by nr23730

Now looks like this:
![Screenshot 2022-05-11 at 13 33 25](https://user-images.githubusercontent.com/20756025/167840216-b5600bc7-587e-44fa-b7a3-141c590eb327.png)

When you are not logged in it looks like this:

![Screenshot 2022-05-11 at 13 33 58](https://user-images.githubusercontent.com/20756025/167840299-187cf475-e83d-4060-a4cf-00481ddb39db.png)

2022-05-18 08:53 UTC, Unberath requested changes

2022-05-18 08:53 UTC, Unberath commented on src/pages/patientView/therapyRecommendation/LoginElements.tsx
> +                className={'fa fa-user-circle'}
I would switch to fa-user-md (as in #79) because the patient icon in the top left corner looks to similar to fa-user-circle.
(fa-user-secret would be another option but it looks a bit off in this context)

2022-05-18 08:53 UTC, Unberath commented on src/pages/patientView/therapyRecommendation/MtbTable.tsx
> +                        {this.state.loggedIn ? (
Right now we don't have any indication why the buttons are disabled when the user isn't logged in. Can we show some hint that editing is not possible without login?
Something like this with a tooltip would be great imho: https://codepen.io/EeKay/pen/JYrGZg

2022-05-19 09:43 UTC, nr23730 commented
@Unberath Done!

2022-05-19 11:35 UTC, Unberath requested changes

2022-05-19 11:35 UTC, Unberath commented on src/pages/patientView/therapyRecommendation/MtbTable.tsx
> +            this.setState({ permission: true });
These changes for testing slipped through ;)

2022-05-19 11:35 UTC, Unberath commented
@nr23730 Just one small issue, other than that it works great. Thanks!

2022-05-19 11:37 UTC, nr23730 commented
@Unberath Resovled! :)

2022-05-19 11:38 UTC, Unberath approved these changes
lgtm!

2022-05-19 11:38 UTC, merged